title: PcapPlusPlus
email: pcapplusplus@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pcapplusplus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: seladb
github_username:  seladb
logo_source: /resources/logo_white.png
logo_width: 180

# Build settings
markdown: kramdown
remote_theme: seladb/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Enable or disable the site search
search_enabled: true

# Enable or disable top navigation panel
top_navigation_enabled: true

# PcapPlusPlus specific variables
pcapplusplus-ver-num: 19.04
pcapplusplus-ver: v19.04

# Google Analytics Tracking
ga_tracking: UA-74037205-2

include:
  - _*_8h.html
  - _*_8h_source.html
  - _*_8h.js

exclude:
  - /api-docs/doxygen/
  - /api-docs/html/
  - README.md

